[profile.default]
libs = ["lib"]
out = "out"
remappings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts", "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"]
src = "src"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[etherscan]
mainnet-basescan = {key = "${BASESCAN_API_KEY}", url = "${BASE_RPC_URL}"}
mainnet-etherscan = {key = "${ETHERSCAN_API_KEY}"}
sepolia-basescan = {key = "${BASESCAN_API_KEY}", url = "${BASE_SEPOLIA_RPC_URL}"}
sepolia-etherscan = {key = "${ETHERSCAN_API_KEY}"}

[rpc_endpoints]
base-rpc = "${BASE_RPC_URL}"
base-sepolia-rpc = "${BASE_SEPOLIA_RPC_URL}"
mainnet-rpc = "${MAINNET_RPC_URL}"
sepolia-rpc = "${SEPOLIA_RPC_URL}"

[invariant]
depth = 64
fail_on_revert = true
runs = 64

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
